# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
    - job: job1
      steps:
      - bash:   echo Build stage1
  - stage: Deploy_to_UAT
    jobs:
    - job: job1_deploy_to_uat
      steps:
      - bash: echo Build stage2 deploy to uat
  - stage: Deploy_to_PRE_PROD
    jobs:
    - job: job1_deploy_to_PRE_PROD
      steps:
      - bash: echo Build stage3 deploy to PRE-PROD
  - stage: Deploy_to_Prod
    jobs:
    - job: job1_deploy_to_PROD
      steps:
      - bash: echo Build stage4 deploy to PROD